import create from 'zustand';

const useColorStore = create((set) => ({
    tailwind_colors : [
        { type: "light", color: "bg-slate-200" },
        { type: "light", color: "bg-slate-300" },
        { type: "dark", color: "bg-slate-400" },
        { type: "light", color: "bg-gray-200" },
        { type: "light", color: "bg-gray-300" },
        { type: "dark", color: "bg-gray-400" },
        { type: "light", color: "bg-zinc-200" },
        { type: "light", color: "bg-zinc-300" },
      //  { type: "dark", color: "bg-zinc-400" },
        //{ type: "light", color: "bg-neutral-200" },
        { type: "light", color: "bg-neutral-300" },
        { type: "dark", color: "bg-neutral-400" },
        { type: "light", color: "bg-stone-200" },
        { type: "light", color: "bg-stone-300" },
        { type: "dark", color: "bg-stone-400" },
        { type: "light", color: "bg-red-200" },
        { type: "light", color: "bg-red-300" },
        { type: "dark", color: "bg-red-400" },
        { type: "light", color: "bg-orange-200" },
        { type: "light", color: "bg-orange-300" },
        { type: "dark", color: "bg-orange-400" },
        { type: "light", color: "bg-amber-200" },
        { type: "light", color: "bg-amber-300" },
        { type: "dark", color: "bg-amber-400" },
        { type: "light", color: "bg-yellow-200" },
        { type: "light", color: "bg-yellow-300" },
        { type: "dark", color: "bg-yellow-400" },
        { type: "light", color: "bg-lime-200" },
        { type: "light", color: "bg-lime-300" },
        { type: "dark", color: "bg-lime-400" },
        { type: "light", color: "bg-green-200" },
        { type: "light", color: "bg-green-300" },
        { type: "dark", color: "bg-green-400" },
        { type: "light", color: "bg-emerald-200" },
        { type: "light", color: "bg-emerald-300" },
        { type: "dark", color: "bg-emerald-400" },
        { type: "light", color: "bg-teal-200" },
        { type: "light", color: "bg-teal-300" },
        { type: "dark", color: "bg-teal-400" },
        { type: "light", color: "bg-cyan-200" },
        { type: "light", color: "bg-cyan-300" },
        { type: "dark", color: "bg-cyan-400" },
        { type: "light", color: "bg-sky-200" },
        { type: "light", color: "bg-sky-300" },
        { type: "dark", color: "bg-sky-400" },
        { type: "light", color: "bg-blue-200" },
        { type: "light", color: "bg-blue-300" },
        { type: "dark", color: "bg-blue-400" },
        { type: "light", color: "bg-indigo-200" },
        { type: "light", color: "bg-indigo-300" },
        { type: "dark", color: "bg-indigo-400" },
        { type: "light", color: "bg-violet-200" },
        { type: "light", color: "bg-violet-300" },
        { type: "dark", color: "bg-violet-400" },
        { type: "light", color: "bg-purple-200" },
        { type: "light", color: "bg-purple-300" },
        { type: "dark", color: "bg-purple-400" },
        { type: "light", color: "bg-fuchsia-200" },
        { type: "light", color: "bg-fuchsia-300" },
        { type: "dark", color: "bg-fuchsia-400" },
        { type: "light", color: "bg-pink-200" },
        { type: "light", color: "bg-pink-300" },
        { type: "dark", color: "bg-pink-400" },
        { type: "light", color: "bg-rose-200" },
        { type: "light", color: "bg-rose-300" },
        { type: "dark", color: "bg-rose-400" },
      ]
}));

export default useColorStore;
